version: '3.4'

services:
  webtest:
    image: ${DOCKER_REGISTRY-}webtest
    build:
      context: .
      dockerfile: WebTest/Dockerfile
    depends_on:
        - selenium-firefox
        - websut
  websut:
    image: ${DOCKER_REGISTRY-}websut
    build:
      context: .
      dockerfile: WebSUT/Dockerfile
    
  selenium-firefox:
    image: "selenium/standalone-firefox:3.141.59"
    ports:
        - "4444:4444"
    shm_size: 2G
